const sampleSongs = [
  { title: "Ocean Eyes", artist: "Billie Eilish", album: "Don't Smile at Me" },
  { title: "Shape of You", artist: "Ed Sheeran", album: "÷ (Divide)" },
  { title: "Blinding Lights", artist: "The Weeknd", album: "After Hours" },
  { title: "Someone Like You", artist: "Adele", album: "21" },
  { title: "Rolling in the Deep", artist: "Adele", album: "21" },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", album: "A Star Is Born" },
  { title: "All of Me", artist: "John Legend", album: "Love in the Future" },
  { title: "Stay", artist: "Rihanna ft. Mikky Ekko", album: "Unapologetic" },
  { title: "Perfect", artist: "Ed Sheeran", album: "÷ (Divide)" },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", album: "Uptown Special" },
  { title: "Dance Monkey", artist: "Tones and I", album: "The Kids Are Coming" },
  { title: "Bad Guy", artist: "Billie Eilish", album: "When We All Fall Asleep, Where Do We Go?" },
  { title: "Watermelon Sugar", artist: "Harry Styles", album: "Fine Line" },
  { title: "Senorita", artist: "Shawn Mendes & Camila Cabello", album: "Shawn Mendes" },
  { title: "Fight Song", artist: "Rachel Platten", album: "Wildfire" },
  { title: "Girls Like You", artist: "Maroon 5 ft. Cardi B", album: "Red Pill Blues" },
  { title: "Say You Won't Let Go", artist: "James Arthur", album: "Back from the Edge" },
  { title: "Take Me to Church", artist: "Hozier", album: "Hozier" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", album: "x (Multiply)" },
  { title: "Radioactive", artist: "Imagine Dragons", album: "Night Visions" },
  { title: "Counting Stars", artist: "OneRepublic", album: "Native" },
  { title: "Somebody That I Used to Know", artist: "Gotye", album: "Making Mirrors" },
  { title: "A Thousand Years", artist: "Christina Perri", album: "The Twilight Saga: Breaking Dawn – Part 1" },
  { title: "Don't Start Now", artist: "Dua Lipa", album: "Future Nostalgia" },
  { title: "Riptide", artist: "Vance Joy", album: "Dream Your Life Away" },
  { title: "Lose You to Love Me", artist: "Selena Gomez", album: "Rare" },
  { title: "Love Yourself", artist: "Justin Bieber", album: "Purpose" },
  { title: "We Don't Talk Anymore", artist: "Charlie Puth ft. Selena Gomez", album: "Nine Track Mind" },
  { title: "Let Her Go", artist: "Passenger", album: "All the Little Lights" },
  { title: "Chasing Cars", artist: "Snow Patrol", album: "Eyes Open" },
  { title: "Halo", artist: "Beyoncé", album: "I Am... Sasha Fierce" },
  { title: "Breathe", artist: "Faith Hill", album: "Breathe" },
  { title: "Happier", artist: "Marshmello ft. Bastille", album: "Happier" },
  { title: "Someone You Loved", artist: "Lewis Capaldi", album: "Divinely Uninspired to a Hellish Extent" },
  { title: "Young Dumb & Broke", artist: "Khalid", album: "American Teen" },
  { title: "Ocean", artist: "Martin Garrix ft. Khalid", album: "Ocean" },
  { title: "Stay with Me", artist: "Sam Smith", album: "In the Lonely Hour" },
  { title: "Peaches", artist: "Justin Bieber ft. Daniel Caesar & Giveon", album: "Justice" },
  { title: "Heart Attack", artist: "Demi Lovato", album: "Demi" },
  { title: "Dusk Till Dawn", artist: "Zayn ft. Sia", album: "Icarus Falls" },
  { title: "In My Feelings", artist: "Drake", album: "Scorpion" },
  { title: "Thank U, Next", artist: "Ariana Grande", album: "Thank U, Next" },
  { title: "Cool for the Summer", artist: "Demi Lovato", album: "Confident" },
  { title: "Blow", artist: "Kesha ft. Pitbull", album: "Animal" },
  { title: "Into You", artist: "Ariana Grande", album: "Dangerous Woman" },
  { title: "I Will Always Love You", artist: "Whitney Houston", album: "The Bodyguard" },
  { title: "Everything I Do (I Do It for You)", artist: "Bryan Adams", album: "Waking Up the Neighbours" },
  { title: "Ain't Nobody", artist: "Chaka Khan", album: "I Feel for You" },
  { title: "Unchained Melody", artist: "The Righteous Brothers", album: "Just Once in My Life" },
  { title: "Kiss from a Rose", artist: "Seal", album: "Seal II" },
  { title: "My Heart Will Go On", artist: "Celine Dion", album: "Let's Talk About Love" },
  { title: "You're Beautiful", artist: "James Blunt", album: "Back to Bedlam" },
  { title: "Time After Time", artist: "Cyndi Lauper", album: "She's So Unusual" },
  { title: "The Way You Make Me Feel", artist: "Michael Jackson", album: "Bad" },
  { title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", album: "I Do Not Want What I Haven't Got" },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", album: "Armageddon" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", album: "Appetite for Destruction" },
  { title: "Billie Jean", artist: "Michael Jackson", album: "Thriller" },
  { title: "Back to Black", artist: "Amy Winehouse", album: "Back to Black" },
  { title: "Seven Nation Army", artist: "The White Stripes", album: "Elephant" },
  { title: "Dreams", artist: "Fleetwood Mac", album: "Rumours" },
  { title: "Take It Easy", artist: "Eagles", album: "Eagles" },
  { title: "Don't Stop Believin'", artist: "Journey", album: "Escape" },
  { title: "Born to Run", artist: "Bruce Springsteen", album: "Born to Run" },
  { title: "Every Breath You Take", artist: "The Police", album: "Synchronicity" },
  { title: "Come Together", artist: "The Beatles", album: "Abbey Road" },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", album: "Highway 61 Revisited" },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", album: "Led Zeppelin IV" },
  { title: "The Sound of Silence", artist: "Simon & Garfunkel", album: "Wednesday Morning, 3 A.M." },
  { title: "Superstition", artist: "Stevie Wonder", album: "Talking Book" },
  { title: "Imagine", artist: "John Lennon", album: "Imagine" },
  { title: "Hotel California", artist: "Eagles", album: "Hotel California" },
  { title: "Wish You Were Here", artist: "Pink Floyd", album: "Wish You Were Here" },
  { title: "Smoke on the Water", artist: "Deep Purple", album: "Machine Head" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", album: "Slippery When Wet" },
  { title: "The Joker", artist: "Steve Miller Band", album: "The Joker" },
  { title: "Eye of the Tiger", artist: "Survivor", album: "Rocky III" },
  { title: "We Will Rock You", artist: "Queen", album: "News of the World" },
  { title: "Thunderstruck", artist: "AC/DC", album: "The Razors Edge" },
  { title: "Satisfaction", artist: "The Rolling Stones", album: "Out of Our Heads" },
  { title: "I Want to Hold Your Hand", artist: "The Beatles", album: "Meet The Beatles!" },
  { title: "Rock and Roll All Nite", artist: "Kiss", album: "Destroyer" },
  { title: "Born to Be Wild", artist: "Steppenwolf", album: "Steppenwolf" },
  { title: "The Twist", artist: "Chubby Checker", album: "Twist with Chubby Checker" },
  { title: "Mack the Knife", artist: "Bobby Darin", album: "That's All" },
  { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", album: "Jerry Lee's Greatest" },
  { title: "Jailhouse Rock", artist: "Elvis Presley", album: "Jailhouse Rock" },
  { title: "My Girl", artist: "The Temptations", album: "The Temptations Sing Smokey" },
  { title: "The Tracks of My Tears", artist: "The Miracles", album: "Going to a Go-Go" },
  { title: "What's Going On", artist: "Marvin Gaye", album: "What's Going On" },
  { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", album: "In the Groove" },
  { title: "Respect", artist: "Aretha Franklin", album: "I Never Loved a Man the Way I Love You" },
  { title: "Superstition", artist: "Stevie Wonder", album: "Talking Book" },
  { title: "You Are the Sunshine of My Life", artist: "Stevie Wonder", album: "Talking Book" }
];


export default sampleSongs;

